<?php

/**
 * @file
 * Contains cfp_user_register.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cfp_user_register_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cfp_user_register module.
    case 'help.page.cfp_user_register':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User register for CFP') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cfp_user_register_theme() {
  return [
    'cfp_user_register' => [
      'render element' => 'children',
    ],
  ];
}
